"""Contains all the data models used in inputs/outputs"""

from .account_info_response_model import AccountInfoResponseModel
from .account_info_response_object import AccountInfoResponseObject
from .airdrop_airdrop_object import AirdropAirdropObject
from .airdrop_response_model import AirdropResponseModel
from .airdrop_results_map import AirdropResultsMap
from .airdrops_airdrop_object import AirdropsAirdropObject
from .airdrops_response_model import AirdropsResponseModel
from .altcoin_season_index_historical_point_object import AltcoinSeasonIndexHistoricalPointObject
from .altcoin_season_index_historical_response_model import AltcoinSeasonIndexHistoricalResponseModel
from .altcoin_season_index_historical_response_object import AltcoinSeasonIndexHistoricalResponseObject
from .altcoin_season_index_latest_response_model import AltcoinSeasonIndexLatestResponseModel
from .altcoin_season_index_latest_response_object import AltcoinSeasonIndexLatestResponseObject
from .api_response_object import ApiResponseObject
from .api_response_object_data import ApiResponseObjectData
from .api_response_of_cmc20_index_historical_response_dto import ApiResponseOfCMC20IndexHistoricalResponseDTO
from .api_response_of_cmc20_index_latest_response_dto import ApiResponseOfCMC20IndexLatestResponseDTO
from .api_response_of_index_historical_response_dto import ApiResponseOfIndexHistoricalResponseDTO
from .api_response_of_index_latest_response_dto import ApiResponseOfIndexLatestResponseDTO
from .api_status_object import APIStatusObject
from .assets import Assets
from .blockchain_statistics_latest_blockchain_object import BlockchainStatisticsLatestBlockchainObject
from .blockchain_statistics_latest_response_model import BlockchainStatisticsLatestResponseModel
from .blockchain_statistics_latest_results_map import BlockchainStatisticsLatestResultsMap
from .bn_security_extra_info_dto import BnSecurityExtraInfoDTO
from .categories_category_object import CategoriesCategoryObject
from .categories_response_model import CategoriesResponseModel
from .category_cryptocurrency_object import CategoryCryptocurrencyObject
from .category_response_model import CategoryResponseModel
from .category_results_map import CategoryResultsMap
from .cmc20_index_detail_dto import CMC20IndexDetailDTO
from .cmc20_index_historical_dto import CMC20IndexHistoricalDTO
from .cmc20_index_latest_dto import CMC20IndexLatestDTO
from .coin import Coin
from .common_batch_request_dto import CommonBatchRequestDTO
from .community_trending_token_response_model import CommunityTrendingTokenResponseModel
from .community_trending_token_results_object import CommunityTrendingTokenResultsObject
from .community_trending_topic_response_model import CommunityTrendingTopicResponseModel
from .community_trending_topic_results import CommunityTrendingTopicResults
from .content_latest_posts_response_model import ContentLatestPostsResponseModel
from .content_latest_response_model import ContentLatestResponseModel
from .content_post_comments_response_model import ContentPostCommentsResponseModel
from .content_top_posts_response_model import ContentTopPostsResponseModel
from .content_top_posts_results import ContentTopPostsResults
from .crypto_currency_exchange_dto import CryptoCurrencyExchangeDTO
from .crypto_listing_dto import CryptoListingDTO
from .crypto_ohlcv_quote_dto import CryptoOhlcvQuoteDTO
from .crypto_quote_dto import CryptoQuoteDTO
from .crypto_quote_v3dto import CryptoQuoteV3DTO
from .crypto_snapshot_dto import CryptoSnapshotDTO
from .crypto_tag import CryptoTag
from .cryptocurrencies_info_cryptocurrency_object_please_note_this_will_be_wrapped_in_an_array_if_you_request_by_symbol_using_the_v2_endpoint import (
    CryptocurrenciesInfoCryptocurrencyObjectPleaseNoteThisWillBeWrappedInAnArrayIfYouRequestBySymbolUsingTheV2Endpoint,
)
from .cryptocurrencies_info_cryptocurrency_object_please_note_this_will_be_wrapped_in_an_array_if_you_request_by_symbol_using_the_v2_endpoint_category import (
    CryptocurrenciesInfoCryptocurrencyObjectPleaseNoteThisWillBeWrappedInAnArrayIfYouRequestBySymbolUsingTheV2EndpointCategory,
)
from .cryptocurrencies_info_response_model import CryptocurrenciesInfoResponseModel
from .cryptocurrencies_info_ur_ls_object import CryptocurrenciesInfoURLsObject
from .cryptocurrency_cryptocurrency_object import CryptocurrencyCryptocurrencyObject
from .cryptocurrency_info_results_map import CryptocurrencyInfoResultsMap
from .cryptocurrency_listings_latest_cryptocurrency_object import CryptocurrencyListingsLatestCryptocurrencyObject
from .cryptocurrency_listings_latest_cryptocurrency_object_1 import CryptocurrencyListingsLatestCryptocurrencyObject1
from .cryptocurrency_listings_latest_cryptocurrency_object_2 import CryptocurrencyListingsLatestCryptocurrencyObject2
from .cryptocurrency_listings_latest_quote_map import CryptocurrencyListingsLatestQuoteMap
from .cryptocurrency_listings_latest_quote_map_1 import CryptocurrencyListingsLatestQuoteMap1
from .cryptocurrency_listings_latest_quote_map_2 import CryptocurrencyListingsLatestQuoteMap2
from .cryptocurrency_listings_latest_quote_object import CryptocurrencyListingsLatestQuoteObject
from .cryptocurrency_listings_latest_quote_object_1 import CryptocurrencyListingsLatestQuoteObject1
from .cryptocurrency_listings_latest_quote_object_2 import CryptocurrencyListingsLatestQuoteObject2
from .cryptocurrency_listings_latest_response_model import CryptocurrencyListingsLatestResponseModel
from .cryptocurrency_listings_latest_response_model_1 import CryptocurrencyListingsLatestResponseModel1
from .cryptocurrency_listings_new_response_model import CryptocurrencyListingsNewResponseModel
from .cryptocurrency_map_cryotocurrency_object import CryptocurrencyMapCryotocurrencyObject
from .cryptocurrency_map_cryotocurrency_object_status import CryptocurrencyMapCryotocurrencyObjectStatus
from .cryptocurrency_map_response_model import CryptocurrencyMapResponseModel
from .cryptocurrency_market_pairs_latest_exchange_info_object import CryptocurrencyMarketPairsLatestExchangeInfoObject
from .cryptocurrency_market_pairs_latest_market_pair_exchange_reported_quote import (
    CryptocurrencyMarketPairsLatestMarketPairExchangeReportedQuote,
)
from .cryptocurrency_market_pairs_latest_market_pair_info_object import (
    CryptocurrencyMarketPairsLatestMarketPairInfoObject,
)
from .cryptocurrency_market_pairs_latest_market_pair_info_object_category import (
    CryptocurrencyMarketPairsLatestMarketPairInfoObjectCategory,
)
from .cryptocurrency_market_pairs_latest_market_pair_info_object_fee_type import (
    CryptocurrencyMarketPairsLatestMarketPairInfoObjectFeeType,
)
from .cryptocurrency_market_pairs_latest_market_pair_quote import CryptocurrencyMarketPairsLatestMarketPairQuote
from .cryptocurrency_market_pairs_latest_market_pair_quote_object import (
    CryptocurrencyMarketPairsLatestMarketPairQuoteObject,
)
from .cryptocurrency_market_pairs_latest_pair_base_currency_info_object import (
    CryptocurrencyMarketPairsLatestPairBaseCurrencyInfoObject,
)
from .cryptocurrency_market_pairs_latest_pair_base_currency_info_object_1 import (
    CryptocurrencyMarketPairsLatestPairBaseCurrencyInfoObject1,
)
from .cryptocurrency_market_pairs_latest_pair_base_currency_info_object_1_currency_type import (
    CryptocurrencyMarketPairsLatestPairBaseCurrencyInfoObject1CurrencyType,
)
from .cryptocurrency_market_pairs_latest_pair_base_currency_info_object_currency_type import (
    CryptocurrencyMarketPairsLatestPairBaseCurrencyInfoObjectCurrencyType,
)
from .cryptocurrency_market_pairs_latest_response_model import CryptocurrencyMarketPairsLatestResponseModel
from .cryptocurrency_market_pairs_latest_results_object import CryptocurrencyMarketPairsLatestResultsObject
from .cryptocurrency_multiplier_data_object import CryptocurrencyMultiplierDataObject
from .cryptocurrency_multiplier_item_object import CryptocurrencyMultiplierItemObject
from .cryptocurrency_multiplier_response_model import CryptocurrencyMultiplierResponseModel
from .cryptocurrency_ohlcv_historical_interval_quote_object import CryptocurrencyOHLCVHistoricalIntervalQuoteObject
from .cryptocurrency_ohlcv_historical_quote_map import CryptocurrencyOHLCVHistoricalQuoteMap
from .cryptocurrency_ohlcv_historical_quote_object import CryptocurrencyOHLCVHistoricalQuoteObject
from .cryptocurrency_ohlcv_historical_response_model import CryptocurrencyOHLCVHistoricalResponseModel
from .cryptocurrency_ohlcv_historical_results_object import CryptocurrencyOHLCVHistoricalResultsObject
from .cryptocurrency_ohlcv_latest_cryptocurrency_object import CryptocurrencyOHLCVLatestCryptocurrencyObject
from .cryptocurrency_ohlcv_latest_cryptocurrency_results_map import CryptocurrencyOHLCVLatestCryptocurrencyResultsMap
from .cryptocurrency_ohlcv_latest_quote_map import CryptocurrencyOHLCVLatestQuoteMap
from .cryptocurrency_ohlcv_latest_quote_object import CryptocurrencyOHLCVLatestQuoteObject
from .cryptocurrency_ohlcv_latest_response_model import CryptocurrencyOHLCVLatestResponseModel
from .cryptocurrency_price_performance_stats_latest_cryptocurrency_object import (
    CryptocurrencyPricePerformanceStatsLatestCryptocurrencyObject,
)
from .cryptocurrency_price_performance_stats_latest_cryptocurrency_results_map import (
    CryptocurrencyPricePerformanceStatsLatestCryptocurrencyResultsMap,
)
from .cryptocurrency_price_performance_stats_latest_period_object import (
    CryptocurrencyPricePerformanceStatsLatestPeriodObject,
)
from .cryptocurrency_price_performance_stats_latest_period_object_map import (
    CryptocurrencyPricePerformanceStatsLatestPeriodObjectMap,
)
from .cryptocurrency_price_performance_stats_latest_quote_map import CryptocurrencyPricePerformanceStatsLatestQuoteMap
from .cryptocurrency_price_performance_stats_latest_quote_object import (
    CryptocurrencyPricePerformanceStatsLatestQuoteObject,
)
from .cryptocurrency_price_performance_stats_latest_response_model import (
    CryptocurrencyPricePerformanceStatsLatestResponseModel,
)
from .cryptocurrency_quote_map import CryptocurrencyQuoteMap
from .cryptocurrency_quote_object import CryptocurrencyQuoteObject
from .cryptocurrency_quotes_historical_currency_quote_object import CryptocurrencyQuotesHistoricalCurrencyQuoteObject
from .cryptocurrency_quotes_historical_interval_quote_object import CryptocurrencyQuotesHistoricalIntervalQuoteObject
from .cryptocurrency_quotes_historical_quote_currency_map import CryptocurrencyQuotesHistoricalQuoteCurrencyMap
from .cryptocurrency_quotes_historical_response_model import CryptocurrencyQuotesHistoricalResponseModel
from .cryptocurrency_quotes_historical_result_object import CryptocurrencyQuotesHistoricalResultObject
from .cryptocurrency_quotes_historical_results_map import CryptocurrencyQuotesHistoricalResultsMap
from .cryptocurrency_quotes_latest_cryptocurrency_object import CryptocurrencyQuotesLatestCryptocurrencyObject
from .cryptocurrency_quotes_latest_cryptocurrency_results_map import CryptocurrencyQuotesLatestCryptocurrencyResultsMap
from .cryptocurrency_quotes_latest_quote_map import CryptocurrencyQuotesLatestQuoteMap
from .cryptocurrency_quotes_latest_quote_object import CryptocurrencyQuotesLatestQuoteObject
from .cryptocurrency_quotes_latest_response_model import CryptocurrencyQuotesLatestResponseModel
from .cryptocurrency_trending_gainers_losers_response_model import CryptocurrencyTrendingGainersLosersResponseModel
from .cryptocurrency_trending_latest_cryptocurrency_object import CryptocurrencyTrendingLatestCryptocurrencyObject
from .cryptocurrency_trending_latest_response_model import CryptocurrencyTrendingLatestResponseModel
from .cryptocurrency_trending_most_visited_response_model import CryptocurrencyTrendingMostVisitedResponseModel
from .current_day import CurrentDay
from .current_minute import CurrentMinute
from .current_month import CurrentMonth
from .derivatives_crypto_market_pairs_list_latest_response_model import (
    DerivativesCryptoMarketPairsListLatestResponseModel,
)
from .derivatives_crypto_market_pairs_list_latest_results_object import (
    DerivativesCryptoMarketPairsListLatestResultsObject,
)
from .derivatives_crypto_market_pairs_list_latest_results_object_market_pairs_item import (
    DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItem,
)
from .derivatives_crypto_market_pairs_list_latest_results_object_market_pairs_item_category import (
    DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemCategory,
)
from .derivatives_crypto_market_pairs_list_latest_results_object_market_pairs_item_exchange import (
    DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemExchange,
)
from .derivatives_crypto_market_pairs_list_latest_results_object_market_pairs_item_exchange_reported_quotes_item import (
    DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemExchangeReportedQuotesItem,
)
from .derivatives_crypto_market_pairs_list_latest_results_object_market_pairs_item_fee_type import (
    DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemFeeType,
)
from .derivatives_crypto_market_pairs_list_latest_results_object_market_pairs_item_market_pair_base import (
    DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemMarketPairBase,
)
from .derivatives_crypto_market_pairs_list_latest_results_object_market_pairs_item_market_pair_base_currency_type import (
    DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemMarketPairBaseCurrencyType,
)
from .derivatives_crypto_market_pairs_list_latest_results_object_market_pairs_item_market_pair_quote import (
    DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemMarketPairQuote,
)
from .derivatives_crypto_market_pairs_list_latest_results_object_market_pairs_item_market_pair_quote_currency_type import (
    DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemMarketPairQuoteCurrencyType,
)
from .derivatives_crypto_market_pairs_list_latest_results_object_market_pairs_item_quotes_item import (
    DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemQuotesItem,
)
from .derivatives_exchanges_list_response_model import DerivativesExchangesListResponseModel
from .derivatives_exchanges_list_results_object import DerivativesExchangesListResultsObject
from .derivatives_exchanges_list_results_object_exchanges_item import DerivativesExchangesListResultsObjectExchangesItem
from .derivatives_exchanges_list_results_object_exchanges_item_quotes_item import (
    DerivativesExchangesListResultsObjectExchangesItemQuotesItem,
)
from .derivatives_market_pairs_list_latest_response_model import DerivativesMarketPairsListLatestResponseModel
from .derivatives_market_pairs_list_latest_results_object import DerivativesMarketPairsListLatestResultsObject
from .derivatives_market_pairs_list_latest_results_object_market_pairs_item import (
    DerivativesMarketPairsListLatestResultsObjectMarketPairsItem,
)
from .derivatives_market_pairs_list_latest_results_object_market_pairs_item_category import (
    DerivativesMarketPairsListLatestResultsObjectMarketPairsItemCategory,
)
from .derivatives_market_pairs_list_latest_results_object_market_pairs_item_exchange_reported_quotes_item import (
    DerivativesMarketPairsListLatestResultsObjectMarketPairsItemExchangeReportedQuotesItem,
)
from .derivatives_market_pairs_list_latest_results_object_market_pairs_item_fee_type import (
    DerivativesMarketPairsListLatestResultsObjectMarketPairsItemFeeType,
)
from .derivatives_market_pairs_list_latest_results_object_market_pairs_item_market_pair_base import (
    DerivativesMarketPairsListLatestResultsObjectMarketPairsItemMarketPairBase,
)
from .derivatives_market_pairs_list_latest_results_object_market_pairs_item_market_pair_base_currency_type import (
    DerivativesMarketPairsListLatestResultsObjectMarketPairsItemMarketPairBaseCurrencyType,
)
from .derivatives_market_pairs_list_latest_results_object_market_pairs_item_market_pair_quote import (
    DerivativesMarketPairsListLatestResultsObjectMarketPairsItemMarketPairQuote,
)
from .derivatives_market_pairs_list_latest_results_object_market_pairs_item_market_pair_quote_currency_type import (
    DerivativesMarketPairsListLatestResultsObjectMarketPairsItemMarketPairQuoteCurrencyType,
)
from .derivatives_market_pairs_list_latest_results_object_market_pairs_item_quotes_item import (
    DerivativesMarketPairsListLatestResultsObjectMarketPairsItemQuotesItem,
)
from .dex_common_info_dto import DexCommonInfoDTO
from .dex_info_dto import DexInfoDTO
from .dex_info_quote import DexInfoQuote
from .dex_multiplier_data_object import DexMultiplierDataObject
from .dex_multiplier_item_object import DexMultiplierItemObject
from .dex_multiplier_response_model import DexMultiplierResponseModel
from .dex_multiplier_validation_error_object import DexMultiplierValidationErrorObject
from .dex_multiplier_validation_status_object import DexMultiplierValidationStatusObject
from .dex_ohlcv_quote import DexOhlcvQuote
from .dex_pairs_ohlcv_dto import DexPairsOhlcvDTO
from .dex_pairs_ohlcv_historical_dto import DexPairsOhlcvHistoricalDTO
from .dex_pairs_ohlcv_historical_quotes import DexPairsOhlcvHistoricalQuotes
from .dex_pairs_trade_dto import DexPairsTradeDTO
from .dex_paris_quotes_dto import DexParisQuotesDTO
from .dex_quote_dto import DexQuoteDTO
from .dex_spot_pair_dto import DexSpotPairDTO
from .dex_token_signal_dto import DexTokenSignalDTO
from .dex_transaction_dto import DexTransactionDTO
from .dex_transaction_quote_dto import DexTransactionQuoteDTO
from .dex_urls import DexUrls
from .display_item import DisplayItem
from .dquery_batch_price_request_dto import DqueryBatchPriceRequestDTO
from .dquery_batch_token_request_dto import DqueryBatchTokenRequestDTO
from .dquery_holders_detail_request_dto import DqueryHoldersDetailRequestDTO
from .dquery_holders_request_dto import DqueryHoldersRequestDTO
from .dquery_market_request_dto import DqueryMarketRequestDTO
from .dquery_meme_request_dto import DqueryMemeRequestDTO
from .exchange_assets_response_model import ExchangeAssetsResponseModel
from .exchange_assets_wallets_response_model import ExchangeAssetsWalletsResponseModel
from .exchange_batch_request_dto import ExchangeBatchRequestDTO
from .exchange_historical_quotes_currency_quote_object import ExchangeHistoricalQuotesCurrencyQuoteObject
from .exchange_historical_quotes_exchange_object import ExchangeHistoricalQuotesExchangeObject
from .exchange_historical_quotes_nterval_quote_object import ExchangeHistoricalQuotesNtervalQuoteObject
from .exchange_historical_quotes_quote_currency_map import ExchangeHistoricalQuotesQuoteCurrencyMap
from .exchange_historical_quotes_response_model import ExchangeHistoricalQuotesResponseModel
from .exchange_historical_quotes_results_map import ExchangeHistoricalQuotesResultsMap
from .exchange_listings_latest_exchange_object import ExchangeListingsLatestExchangeObject
from .exchange_listings_latest_quote_map import ExchangeListingsLatestQuoteMap
from .exchange_listings_latest_quote_object import ExchangeListingsLatestQuoteObject
from .exchange_listings_latest_response_model import ExchangeListingsLatestResponseModel
from .exchange_map_exchange_object import ExchangeMapExchangeObject
from .exchange_map_exchange_object_status import ExchangeMapExchangeObjectStatus
from .exchange_map_response_model import ExchangeMapResponseModel
from .exchange_market_pairs_latest_market_pair_exchange_reported_quote import (
    ExchangeMarketPairsLatestMarketPairExchangeReportedQuote,
)
from .exchange_market_pairs_latest_market_pair_info_object import ExchangeMarketPairsLatestMarketPairInfoObject
from .exchange_market_pairs_latest_market_pair_info_object_category import (
    ExchangeMarketPairsLatestMarketPairInfoObjectCategory,
)
from .exchange_market_pairs_latest_market_pair_info_object_fee_type import (
    ExchangeMarketPairsLatestMarketPairInfoObjectFeeType,
)
from .exchange_market_pairs_latest_market_pair_quote import ExchangeMarketPairsLatestMarketPairQuote
from .exchange_market_pairs_latest_market_pair_quote_object import ExchangeMarketPairsLatestMarketPairQuoteObject
from .exchange_market_pairs_latest_pair_base_currency_info_object import (
    ExchangeMarketPairsLatestPairBaseCurrencyInfoObject,
)
from .exchange_market_pairs_latest_pair_base_currency_info_object_1 import (
    ExchangeMarketPairsLatestPairBaseCurrencyInfoObject1,
)
from .exchange_market_pairs_latest_pair_base_currency_info_object_1_currency_type import (
    ExchangeMarketPairsLatestPairBaseCurrencyInfoObject1CurrencyType,
)
from .exchange_market_pairs_latest_pair_base_currency_info_object_currency_type import (
    ExchangeMarketPairsLatestPairBaseCurrencyInfoObjectCurrencyType,
)
from .exchange_market_pairs_latest_response_model import ExchangeMarketPairsLatestResponseModel
from .exchange_market_pairs_latest_results_object import ExchangeMarketPairsLatestResultsObject
from .exchange_quote_dto import ExchangeQuoteDTO
from .exchange_quotes_latest_exchange_object import ExchangeQuotesLatestExchangeObject
from .exchange_quotes_latest_exchange_results_map import ExchangeQuotesLatestExchangeResultsMap
from .exchange_quotes_latest_quote_map import ExchangeQuotesLatestQuoteMap
from .exchange_quotes_latest_quote_object import ExchangeQuotesLatestQuoteObject
from .exchange_quotes_latest_response_model import ExchangeQuotesLatestResponseModel
from .exchanges_info_exchange_info_object import ExchangesInfoExchangeInfoObject
from .exchanges_info_response_model import ExchangesInfoResponseModel
from .exchanges_info_results_map import ExchangesInfoResultsMap
from .exchanges_info_ur_ls_object import ExchangesInfoURLsObject
from .fcas_listings_latest_cryptocurrency_object import FCASListingsLatestCryptocurrencyObject
from .fcas_listings_latest_response_model import FCASListingsLatestResponseModel
from .fcas_quote_latest_cryptocurrency_object import FCASQuoteLatestCryptocurrencyObject
from .fcas_quote_latest_cryptocurrency_results_map import FCASQuoteLatestCryptocurrencyResultsMap
from .fcas_quote_latest_response_model import FCASQuoteLatestResponseModel
from .fear_and_greed_historical_fear_and_greed_object import FearAndGreedHistoricalFearAndGreedObject
from .fear_and_greed_historical_response_model import FearAndGreedHistoricalResponseModel
from .fear_and_greed_latest_response_model import FearAndGreedLatestResponseModel
from .fear_and_greed_latest_response_object import FearAndGreedLatestResponseObject
from .fear_greed_historical_dto import FearGreedHistoricalDTO
from .fear_greed_latest_dto import FearGreedLatestDTO
from .fiat_map_fiat_object import FiatMapFiatObject
from .fiat_map_response_model import FiatMapResponseModel
from .gainer_leader_board_response_dto import GainerLeaderBoardResponseDTO
from .get_v1_altcoin_season_index_historical_timeframe import GetV1AltcoinSeasonIndexHistoricalTimeframe
from .get_v1_content_latest_language import GetV1ContentLatestLanguage
from .get_v1_cryptocurrency_airdrops_status import GetV1CryptocurrencyAirdropsStatus
from .get_v1_cryptocurrency_listings_historical_cryptocurrency_type import (
    GetV1CryptocurrencyListingsHistoricalCryptocurrencyType,
)
from .get_v1_cryptocurrency_listings_historical_sort import GetV1CryptocurrencyListingsHistoricalSort
from .get_v1_cryptocurrency_listings_historical_sort_dir import GetV1CryptocurrencyListingsHistoricalSortDir
from .get_v1_cryptocurrency_listings_latest_cryptocurrency_type import (
    GetV1CryptocurrencyListingsLatestCryptocurrencyType,
)
from .get_v1_cryptocurrency_listings_latest_sort import GetV1CryptocurrencyListingsLatestSort
from .get_v1_cryptocurrency_listings_latest_sort_dir import GetV1CryptocurrencyListingsLatestSortDir
from .get_v1_cryptocurrency_listings_latest_tag import GetV1CryptocurrencyListingsLatestTag
from .get_v1_cryptocurrency_listings_new_sort_dir import GetV1CryptocurrencyListingsNewSortDir
from .get_v1_cryptocurrency_map_sort import GetV1CryptocurrencyMapSort
from .get_v1_cryptocurrency_marketpairs_latest_category import GetV1CryptocurrencyMarketpairsLatestCategory
from .get_v1_cryptocurrency_marketpairs_latest_fee_type import GetV1CryptocurrencyMarketpairsLatestFeeType
from .get_v1_cryptocurrency_marketpairs_latest_sort import GetV1CryptocurrencyMarketpairsLatestSort
from .get_v1_cryptocurrency_marketpairs_latest_sort_dir import GetV1CryptocurrencyMarketpairsLatestSortDir
from .get_v1_cryptocurrency_ohlcv_historical_interval import GetV1CryptocurrencyOhlcvHistoricalInterval
from .get_v1_cryptocurrency_ohlcv_historical_time_period import GetV1CryptocurrencyOhlcvHistoricalTimePeriod
from .get_v1_cryptocurrency_quotes_historical_interval import GetV1CryptocurrencyQuotesHistoricalInterval
from .get_v1_cryptocurrency_trending_gainerslosers_sort import GetV1CryptocurrencyTrendingGainerslosersSort
from .get_v1_cryptocurrency_trending_gainerslosers_sort_dir import GetV1CryptocurrencyTrendingGainerslosersSortDir
from .get_v1_cryptocurrency_trending_gainerslosers_time_period import GetV1CryptocurrencyTrendingGainerslosersTimePeriod
from .get_v1_cryptocurrency_trending_latest_time_period import GetV1CryptocurrencyTrendingLatestTimePeriod
from .get_v1_cryptocurrency_trending_mostvisited_time_period import GetV1CryptocurrencyTrendingMostvisitedTimePeriod
from .get_v1_exchange_listings_latest_category import GetV1ExchangeListingsLatestCategory
from .get_v1_exchange_listings_latest_market_type import GetV1ExchangeListingsLatestMarketType
from .get_v1_exchange_listings_latest_sort import GetV1ExchangeListingsLatestSort
from .get_v1_exchange_listings_latest_sort_dir import GetV1ExchangeListingsLatestSortDir
from .get_v1_exchange_map_sort import GetV1ExchangeMapSort
from .get_v1_exchange_marketpairs_latest_category import GetV1ExchangeMarketpairsLatestCategory
from .get_v1_exchange_marketpairs_latest_fee_type import GetV1ExchangeMarketpairsLatestFeeType
from .get_v1_exchange_quotes_historical_interval import GetV1ExchangeQuotesHistoricalInterval
from .get_v1_fiat_map_sort import GetV1FiatMapSort
from .get_v1_globalmetrics_quotes_historical_interval import GetV1GlobalmetricsQuotesHistoricalInterval
from .get_v2_cryptocurrency_marketpairs_latest_category import GetV2CryptocurrencyMarketpairsLatestCategory
from .get_v2_cryptocurrency_marketpairs_latest_fee_type import GetV2CryptocurrencyMarketpairsLatestFeeType
from .get_v2_cryptocurrency_marketpairs_latest_sort import GetV2CryptocurrencyMarketpairsLatestSort
from .get_v2_cryptocurrency_marketpairs_latest_sort_dir import GetV2CryptocurrencyMarketpairsLatestSortDir
from .get_v2_cryptocurrency_ohlcv_historical_interval import GetV2CryptocurrencyOhlcvHistoricalInterval
from .get_v2_cryptocurrency_ohlcv_historical_time_period import GetV2CryptocurrencyOhlcvHistoricalTimePeriod
from .get_v2_cryptocurrency_quotes_historical_interval import GetV2CryptocurrencyQuotesHistoricalInterval
from .get_v3_cryptocurrency_listings_latest_response_200 import GetV3CryptocurrencyListingsLatestResponse200
from .get_v3_cryptocurrency_quotes_historical_interval import GetV3CryptocurrencyQuotesHistoricalInterval
from .get_v5_cryptocurrency_derivatives_market_pairs_list_latest_category import (
    GetV5CryptocurrencyDerivativesMarketPairsListLatestCategory,
)
from .get_v5_cryptocurrency_derivatives_market_pairs_list_latest_center_type import (
    GetV5CryptocurrencyDerivativesMarketPairsListLatestCenterType,
)
from .get_v5_cryptocurrency_derivatives_market_pairs_list_latest_fee_type import (
    GetV5CryptocurrencyDerivativesMarketPairsListLatestFeeType,
)
from .get_v5_cryptocurrency_derivatives_market_pairs_list_latest_sort import (
    GetV5CryptocurrencyDerivativesMarketPairsListLatestSort,
)
from .get_v5_cryptocurrency_derivatives_market_pairs_list_latest_sort_dir import (
    GetV5CryptocurrencyDerivativesMarketPairsListLatestSortDir,
)
from .get_v5_derivatives_liquidations_cryptocurrency_list_latest_sort import (
    GetV5DerivativesLiquidationsCryptocurrencyListLatestSort,
)
from .get_v5_derivatives_liquidations_cryptocurrency_list_latest_sort_dir import (
    GetV5DerivativesLiquidationsCryptocurrencyListLatestSortDir,
)
from .get_v5_derivatives_liquidations_exchange_list_latest_sort import (
    GetV5DerivativesLiquidationsExchangeListLatestSort,
)
from .get_v5_derivatives_liquidations_exchange_list_latest_sort_dir import (
    GetV5DerivativesLiquidationsExchangeListLatestSortDir,
)
from .get_v5_exchange_derivatives_list_sort import GetV5ExchangeDerivativesListSort
from .get_v5_exchange_derivatives_list_sort_dir import GetV5ExchangeDerivativesListSortDir
from .get_v5_exchange_derivatives_market_pairs_list_latest_category import (
    GetV5ExchangeDerivativesMarketPairsListLatestCategory,
)
from .get_v5_exchange_derivatives_market_pairs_list_latest_fee_type import (
    GetV5ExchangeDerivativesMarketPairsListLatestFeeType,
)
from .get_v5_exchange_derivatives_market_pairs_list_latest_sort import GetV5ExchangeDerivativesMarketPairsListLatestSort
from .get_v5_exchange_derivatives_market_pairs_list_latest_sort_dir import (
    GetV5ExchangeDerivativesMarketPairsListLatestSortDir,
)
from .get_v5_real_world_assets_assets_list_asset_type import GetV5RealWorldAssetsAssetsListAssetType
from .get_v5_real_world_assets_assets_list_sort import GetV5RealWorldAssetsAssetsListSort
from .get_v5_real_world_assets_assets_list_sort_dir import GetV5RealWorldAssetsAssetsListSortDir
from .get_v5_real_world_assets_map_asset_type import GetV5RealWorldAssetsMapAssetType
from .get_v5_real_world_assets_map_sort import GetV5RealWorldAssetsMapSort
from .get_v5_real_world_assets_market_pairs_list_sort import GetV5RealWorldAssetsMarketPairsListSort
from .get_v5_real_world_assets_market_pairs_list_sort_dir import GetV5RealWorldAssetsMarketPairsListSortDir
from .global_metrics_batch_request_dto import GlobalMetricsBatchRequestDTO
from .global_metrics_quote_dto import GlobalMetricsQuoteDTO
from .global_metrics_quotes_historic_currency_quote_object import GlobalMetricsQuotesHistoricCurrencyQuoteObject
from .global_metrics_quotes_historic_interval_quote_object import GlobalMetricsQuotesHistoricIntervalQuoteObject
from .global_metrics_quotes_historic_quote_currency_map import GlobalMetricsQuotesHistoricQuoteCurrencyMap
from .global_metrics_quotes_historic_response_model import GlobalMetricsQuotesHistoricResponseModel
from .global_metrics_quotes_historic_results_object import GlobalMetricsQuotesHistoricResultsObject
from .global_metrics_quotes_latest_quote_map import GlobalMetricsQuotesLatestQuoteMap
from .global_metrics_quotes_latest_quote_object import GlobalMetricsQuotesLatestQuoteObject
from .global_metrics_quotes_latest_response_model import GlobalMetricsQuotesLatestResponseModel
from .global_metrics_quotes_latest_results_object import GlobalMetricsQuotesLatestResultsObject
from .holder_count_vo import HolderCountVO
from .holder_detail_vo import HolderDetailVO
from .holder_dex_vo import HolderDexVO
from .holder_tag_count_vo import HolderTagCountVO
from .holder_tag_item import HolderTagItem
from .holder_trend_vo import HolderTrendVO
from .http_status_400_error_object import HTTPStatus400ErrorObject
from .http_status_401_error_object import HTTPStatus401ErrorObject
from .http_status_403_error_object import HTTPStatus403ErrorObject
from .http_status_429_error_object import HTTPStatus429ErrorObject
from .http_status_500_error_object import HTTPStatus500ErrorObject
from .index_detail_dto import IndexDetailDTO
from .index_historical_dto import IndexHistoricalDTO
from .index_latest_dto import IndexLatestDTO
from .leaderboard_filter_dto import LeaderboardFilterDTO
from .leaderboard_filter_dto_boost_type import LeaderboardFilterDTOBoostType
from .liquidations_by_cryptocurrency_response_model import LiquidationsByCryptocurrencyResponseModel
from .liquidations_by_cryptocurrency_results_object import LiquidationsByCryptocurrencyResultsObject
from .liquidations_by_cryptocurrency_results_object_cryptocurrencies_item import (
    LiquidationsByCryptocurrencyResultsObjectCryptocurrenciesItem,
)
from .liquidations_by_cryptocurrency_results_object_cryptocurrencies_item_quotes_item import (
    LiquidationsByCryptocurrencyResultsObjectCryptocurrenciesItemQuotesItem,
)
from .liquidations_by_exchange_response_model import LiquidationsByExchangeResponseModel
from .liquidations_by_exchange_results_object import LiquidationsByExchangeResultsObject
from .liquidations_by_exchange_results_object_exchanges_item import LiquidationsByExchangeResultsObjectExchangesItem
from .liquidations_by_exchange_results_object_exchanges_item_quotes_item import (
    LiquidationsByExchangeResultsObjectExchangesItemQuotesItem,
)
from .liquidations_total_response_model import LiquidationsTotalResponseModel
from .liquidations_total_results_object import LiquidationsTotalResultsObject
from .liquidations_total_results_object_quotes_item import LiquidationsTotalResultsObjectQuotesItem
from .liquidity_change_dto import LiquidityChangeDTO
from .liquidity_change_list_response_dto import LiquidityChangeListResponseDTO
from .meme_coin_filter_dto import MemeCoinFilterDTO
from .meme_coin_response_dto import MemeCoinResponseDTO
from .meme_coin_result_dto import MemeCoinResultDTO
from .model_1 import Model1
from .model_2 import Model2
from .model_3 import Model3
from .model_4 import Model4
from .network_info_dto import NetworkInfoDTO
from .new_token_leader_board_response_dto import NewTokenLeaderBoardResponseDTO
from .next_unlocked_detail_dto import NextUnlockedDetailDTO
from .next_unlocked_dto import NextUnlockedDTO
from .ohlcv_batch_request_dto import OhlcvBatchRequestDTO
from .owner import Owner
from .plan import Plan
from .platform import Platform
from .platform_address import PlatformAddress
from .platform_dto import PlatformDTO
from .platform_type_0 import PlatformType0
from .pro_api_response_status import ProApiResponseStatus
from .quote import Quote
from .range_filter_dto import RangeFilterDto
from .response_status import ResponseStatus
from .rwa_asset_list_response_model import RWAAssetListResponseModel
from .rwa_asset_list_results_object import RWAAssetListResultsObject
from .rwa_asset_list_results_object_rwa_assets_item import RWAAssetListResultsObjectRwaAssetsItem
from .rwa_asset_list_results_object_rwa_assets_item_asset_type import RWAAssetListResultsObjectRwaAssetsItemAssetType
from .rwa_asset_list_results_object_rwa_assets_item_quotes_item import RWAAssetListResultsObjectRwaAssetsItemQuotesItem
from .rwa_info_response_model import RWAInfoResponseModel
from .rwa_info_results_object import RWAInfoResultsObject
from .rwa_info_results_object_rwa_assets_item import RWAInfoResultsObjectRwaAssetsItem
from .rwa_info_results_object_rwa_assets_item_about import RWAInfoResultsObjectRwaAssetsItemAbout
from .rwa_info_results_object_rwa_assets_item_asset_type import RWAInfoResultsObjectRwaAssetsItemAssetType
from .rwa_issuer_response_model import RWAIssuerResponseModel
from .rwa_issuer_results_object import RWAIssuerResultsObject
from .rwa_issuer_results_object_tokens_item import RWAIssuerResultsObjectTokensItem
from .rwa_issuers_list_response_model import RWAIssuersListResponseModel
from .rwa_issuers_list_results_object import RWAIssuersListResultsObject
from .rwa_issuers_list_results_object_issuers_item import RWAIssuersListResultsObjectIssuersItem
from .rwa_market_pairs_response_model import RWAMarketPairsResponseModel
from .rwa_market_pairs_results_object import RWAMarketPairsResultsObject
from .rwa_market_pairs_results_object_market_pairs_item import RWAMarketPairsResultsObjectMarketPairsItem
from .rwa_market_pairs_results_object_market_pairs_item_category import (
    RWAMarketPairsResultsObjectMarketPairsItemCategory,
)
from .rwa_market_pairs_results_object_market_pairs_item_exchange import (
    RWAMarketPairsResultsObjectMarketPairsItemExchange,
)
from .rwa_market_pairs_results_object_market_pairs_item_exchange_reported_quotes_item import (
    RWAMarketPairsResultsObjectMarketPairsItemExchangeReportedQuotesItem,
)
from .rwa_market_pairs_results_object_market_pairs_item_fee_type import (
    RWAMarketPairsResultsObjectMarketPairsItemFeeType,
)
from .rwa_market_pairs_results_object_market_pairs_item_market_pair_base import (
    RWAMarketPairsResultsObjectMarketPairsItemMarketPairBase,
)
from .rwa_market_pairs_results_object_market_pairs_item_market_pair_base_currency_type import (
    RWAMarketPairsResultsObjectMarketPairsItemMarketPairBaseCurrencyType,
)
from .rwa_market_pairs_results_object_market_pairs_item_market_pair_quote import (
    RWAMarketPairsResultsObjectMarketPairsItemMarketPairQuote,
)
from .rwa_market_pairs_results_object_market_pairs_item_market_pair_quote_currency_type import (
    RWAMarketPairsResultsObjectMarketPairsItemMarketPairQuoteCurrencyType,
)
from .rwa_market_pairs_results_object_market_pairs_item_quotes_item import (
    RWAMarketPairsResultsObjectMarketPairsItemQuotesItem,
)
from .rwa_quotes_latest_response_model import RWAQuotesLatestResponseModel
from .rwa_quotes_latest_results_object import RWAQuotesLatestResultsObject
from .rwa_quotes_latest_results_object_rwa_assets_item import RWAQuotesLatestResultsObjectRwaAssetsItem
from .rwa_quotes_latest_results_object_rwa_assets_item_asset_type import (
    RWAQuotesLatestResultsObjectRwaAssetsItemAssetType,
)
from .rwa_quotes_latest_results_object_rwa_assets_item_quotes_item import (
    RWAQuotesLatestResultsObjectRwaAssetsItemQuotesItem,
)
from .rwa_quotes_latest_results_object_rwa_assets_item_tokens_item import (
    RWAQuotesLatestResultsObjectRwaAssetsItemTokensItem,
)
from .rwa_quotes_latest_results_object_rwa_assets_item_tradfi_markets_item import (
    RWAQuotesLatestResultsObjectRwaAssetsItemTradfiMarketsItem,
)
from .rwa_quotes_latest_results_object_rwa_assets_item_tradfi_markets_item_exchange import (
    RWAQuotesLatestResultsObjectRwaAssetsItemTradfiMarketsItemExchange,
)
from .rwaid_map_response_model import RWAIDMapResponseModel
from .rwaid_map_results_object import RWAIDMapResultsObject
from .rwaid_map_results_object_rwa_assets_item import RWAIDMapResultsObjectRwaAssetsItem
from .rwaid_map_results_object_rwa_assets_item_asset_type import RWAIDMapResultsObjectRwaAssetsItemAssetType
from .search_response_dto import SearchResponseDTO
from .search_result_dto import SearchResultDTO
from .security_item import SecurityItem
from .security_scan_3_rd_result import SecurityScan3RdResult
from .security_scan_aggregated_result import SecurityScanAggregatedResult
from .security_scan_result import SecurityScanResult
from .simple_price_item_object import SimplePriceItemObject
from .simple_price_response_model import SimplePriceResponseModel
from .snapshot_batch_query_request_dto import SnapshotBatchQueryRequestDTO
from .status import Status
from .status_1 import Status1
from .status_2 import Status2
from .status_3 import Status3
from .status_4 import Status4
from .status_4_error_code import Status4ErrorCode
from .swap_list_response_dto import SwapListResponseDTO
from .tag_dto import TagDTO
from .the_blockchain_platform_where_the_assets_are_held_on import TheBlockchainPlatformWhereTheAssetsAreHeldOn
from .the_cryptocurrency_of_the_holdings_in_the_wallet import TheCryptocurrencyOfTheHoldingsInTheWallet
from .token import Token
from .token_detail_dto import TokenDetailDTO
from .token_event_dto import TokenEventDTO
from .token_leaderboard_dto import TokenLeaderboardDTO
from .token_liquidity_snapshot_dto import TokenLiquiditySnapshotDTO
from .token_price_dto import TokenPriceDTO
from .token_security_response_dto import TokenSecurityResponseDTO
from .token_stats_dto import TokenStatsDTO
from .token_top_pool_dto import TokenTopPoolDTO
from .token_unlock_event_dto import TokenUnlockEventDTO
from .token_unlock_info_dto import TokenUnlockInfoDTO
from .tools_price_conversion_quote_object import ToolsPriceConversionQuoteObject
from .tools_price_conversion_quotes_map_please_note_this_will_be_wrapped_in_an_array_if_you_request_by_symbol_using_the_v2_endpoint import (
    ToolsPriceConversionQuotesMapPleaseNoteThisWillBeWrappedInAnArrayIfYouRequestBySymbolUsingTheV2Endpoint,
)
from .tools_price_conversion_response_model import ToolsPriceConversionResponseModel
from .tools_price_conversion_results_object import ToolsPriceConversionResultsObject
from .trade_history_dto import TradeHistoryDTO
from .trending_tokens_response_dto import TrendingTokensResponseDTO
from .usage import Usage
from .v2_simple_price_item_object import V2SimplePriceItemObject
from .v2_simple_price_item_object_quotes_item import V2SimplePriceItemObjectQuotesItem
from .v2_simple_price_response_model import V2SimplePriceResponseModel

__all__ = (
    "AccountInfoResponseModel",
    "AccountInfoResponseObject",
    "AirdropAirdropObject",
    "AirdropResponseModel",
    "AirdropResultsMap",
    "AirdropsAirdropObject",
    "AirdropsResponseModel",
    "AltcoinSeasonIndexHistoricalPointObject",
    "AltcoinSeasonIndexHistoricalResponseModel",
    "AltcoinSeasonIndexHistoricalResponseObject",
    "AltcoinSeasonIndexLatestResponseModel",
    "AltcoinSeasonIndexLatestResponseObject",
    "ApiResponseObject",
    "ApiResponseObjectData",
    "ApiResponseOfCMC20IndexHistoricalResponseDTO",
    "ApiResponseOfCMC20IndexLatestResponseDTO",
    "ApiResponseOfIndexHistoricalResponseDTO",
    "ApiResponseOfIndexLatestResponseDTO",
    "APIStatusObject",
    "Assets",
    "BlockchainStatisticsLatestBlockchainObject",
    "BlockchainStatisticsLatestResponseModel",
    "BlockchainStatisticsLatestResultsMap",
    "BnSecurityExtraInfoDTO",
    "CategoriesCategoryObject",
    "CategoriesResponseModel",
    "CategoryCryptocurrencyObject",
    "CategoryResponseModel",
    "CategoryResultsMap",
    "CMC20IndexDetailDTO",
    "CMC20IndexHistoricalDTO",
    "CMC20IndexLatestDTO",
    "Coin",
    "CommonBatchRequestDTO",
    "CommunityTrendingTokenResponseModel",
    "CommunityTrendingTokenResultsObject",
    "CommunityTrendingTopicResponseModel",
    "CommunityTrendingTopicResults",
    "ContentLatestPostsResponseModel",
    "ContentLatestResponseModel",
    "ContentPostCommentsResponseModel",
    "ContentTopPostsResponseModel",
    "ContentTopPostsResults",
    "CryptocurrenciesInfoCryptocurrencyObjectPleaseNoteThisWillBeWrappedInAnArrayIfYouRequestBySymbolUsingTheV2Endpoint",
    "CryptocurrenciesInfoCryptocurrencyObjectPleaseNoteThisWillBeWrappedInAnArrayIfYouRequestBySymbolUsingTheV2EndpointCategory",
    "CryptocurrenciesInfoResponseModel",
    "CryptocurrenciesInfoURLsObject",
    "CryptocurrencyCryptocurrencyObject",
    "CryptoCurrencyExchangeDTO",
    "CryptocurrencyInfoResultsMap",
    "CryptocurrencyListingsLatestCryptocurrencyObject",
    "CryptocurrencyListingsLatestCryptocurrencyObject1",
    "CryptocurrencyListingsLatestCryptocurrencyObject2",
    "CryptocurrencyListingsLatestQuoteMap",
    "CryptocurrencyListingsLatestQuoteMap1",
    "CryptocurrencyListingsLatestQuoteMap2",
    "CryptocurrencyListingsLatestQuoteObject",
    "CryptocurrencyListingsLatestQuoteObject1",
    "CryptocurrencyListingsLatestQuoteObject2",
    "CryptocurrencyListingsLatestResponseModel",
    "CryptocurrencyListingsLatestResponseModel1",
    "CryptocurrencyListingsNewResponseModel",
    "CryptocurrencyMapCryotocurrencyObject",
    "CryptocurrencyMapCryotocurrencyObjectStatus",
    "CryptocurrencyMapResponseModel",
    "CryptocurrencyMarketPairsLatestExchangeInfoObject",
    "CryptocurrencyMarketPairsLatestMarketPairExchangeReportedQuote",
    "CryptocurrencyMarketPairsLatestMarketPairInfoObject",
    "CryptocurrencyMarketPairsLatestMarketPairInfoObjectCategory",
    "CryptocurrencyMarketPairsLatestMarketPairInfoObjectFeeType",
    "CryptocurrencyMarketPairsLatestMarketPairQuote",
    "CryptocurrencyMarketPairsLatestMarketPairQuoteObject",
    "CryptocurrencyMarketPairsLatestPairBaseCurrencyInfoObject",
    "CryptocurrencyMarketPairsLatestPairBaseCurrencyInfoObject1",
    "CryptocurrencyMarketPairsLatestPairBaseCurrencyInfoObject1CurrencyType",
    "CryptocurrencyMarketPairsLatestPairBaseCurrencyInfoObjectCurrencyType",
    "CryptocurrencyMarketPairsLatestResponseModel",
    "CryptocurrencyMarketPairsLatestResultsObject",
    "CryptocurrencyMultiplierDataObject",
    "CryptocurrencyMultiplierItemObject",
    "CryptocurrencyMultiplierResponseModel",
    "CryptocurrencyOHLCVHistoricalIntervalQuoteObject",
    "CryptocurrencyOHLCVHistoricalQuoteMap",
    "CryptocurrencyOHLCVHistoricalQuoteObject",
    "CryptocurrencyOHLCVHistoricalResponseModel",
    "CryptocurrencyOHLCVHistoricalResultsObject",
    "CryptocurrencyOHLCVLatestCryptocurrencyObject",
    "CryptocurrencyOHLCVLatestCryptocurrencyResultsMap",
    "CryptocurrencyOHLCVLatestQuoteMap",
    "CryptocurrencyOHLCVLatestQuoteObject",
    "CryptocurrencyOHLCVLatestResponseModel",
    "CryptocurrencyPricePerformanceStatsLatestCryptocurrencyObject",
    "CryptocurrencyPricePerformanceStatsLatestCryptocurrencyResultsMap",
    "CryptocurrencyPricePerformanceStatsLatestPeriodObject",
    "CryptocurrencyPricePerformanceStatsLatestPeriodObjectMap",
    "CryptocurrencyPricePerformanceStatsLatestQuoteMap",
    "CryptocurrencyPricePerformanceStatsLatestQuoteObject",
    "CryptocurrencyPricePerformanceStatsLatestResponseModel",
    "CryptocurrencyQuoteMap",
    "CryptocurrencyQuoteObject",
    "CryptocurrencyQuotesHistoricalCurrencyQuoteObject",
    "CryptocurrencyQuotesHistoricalIntervalQuoteObject",
    "CryptocurrencyQuotesHistoricalQuoteCurrencyMap",
    "CryptocurrencyQuotesHistoricalResponseModel",
    "CryptocurrencyQuotesHistoricalResultObject",
    "CryptocurrencyQuotesHistoricalResultsMap",
    "CryptocurrencyQuotesLatestCryptocurrencyObject",
    "CryptocurrencyQuotesLatestCryptocurrencyResultsMap",
    "CryptocurrencyQuotesLatestQuoteMap",
    "CryptocurrencyQuotesLatestQuoteObject",
    "CryptocurrencyQuotesLatestResponseModel",
    "CryptocurrencyTrendingGainersLosersResponseModel",
    "CryptocurrencyTrendingLatestCryptocurrencyObject",
    "CryptocurrencyTrendingLatestResponseModel",
    "CryptocurrencyTrendingMostVisitedResponseModel",
    "CryptoListingDTO",
    "CryptoOhlcvQuoteDTO",
    "CryptoQuoteDTO",
    "CryptoQuoteV3DTO",
    "CryptoSnapshotDTO",
    "CryptoTag",
    "CurrentDay",
    "CurrentMinute",
    "CurrentMonth",
    "DerivativesCryptoMarketPairsListLatestResponseModel",
    "DerivativesCryptoMarketPairsListLatestResultsObject",
    "DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItem",
    "DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemCategory",
    "DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemExchange",
    "DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemExchangeReportedQuotesItem",
    "DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemFeeType",
    "DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemMarketPairBase",
    "DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemMarketPairBaseCurrencyType",
    "DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemMarketPairQuote",
    "DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemMarketPairQuoteCurrencyType",
    "DerivativesCryptoMarketPairsListLatestResultsObjectMarketPairsItemQuotesItem",
    "DerivativesExchangesListResponseModel",
    "DerivativesExchangesListResultsObject",
    "DerivativesExchangesListResultsObjectExchangesItem",
    "DerivativesExchangesListResultsObjectExchangesItemQuotesItem",
    "DerivativesMarketPairsListLatestResponseModel",
    "DerivativesMarketPairsListLatestResultsObject",
    "DerivativesMarketPairsListLatestResultsObjectMarketPairsItem",
    "DerivativesMarketPairsListLatestResultsObjectMarketPairsItemCategory",
    "DerivativesMarketPairsListLatestResultsObjectMarketPairsItemExchangeReportedQuotesItem",
    "DerivativesMarketPairsListLatestResultsObjectMarketPairsItemFeeType",
    "DerivativesMarketPairsListLatestResultsObjectMarketPairsItemMarketPairBase",
    "DerivativesMarketPairsListLatestResultsObjectMarketPairsItemMarketPairBaseCurrencyType",
    "DerivativesMarketPairsListLatestResultsObjectMarketPairsItemMarketPairQuote",
    "DerivativesMarketPairsListLatestResultsObjectMarketPairsItemMarketPairQuoteCurrencyType",
    "DerivativesMarketPairsListLatestResultsObjectMarketPairsItemQuotesItem",
    "DexCommonInfoDTO",
    "DexInfoDTO",
    "DexInfoQuote",
    "DexMultiplierDataObject",
    "DexMultiplierItemObject",
    "DexMultiplierResponseModel",
    "DexMultiplierValidationErrorObject",
    "DexMultiplierValidationStatusObject",
    "DexOhlcvQuote",
    "DexPairsOhlcvDTO",
    "DexPairsOhlcvHistoricalDTO",
    "DexPairsOhlcvHistoricalQuotes",
    "DexPairsTradeDTO",
    "DexParisQuotesDTO",
    "DexQuoteDTO",
    "DexSpotPairDTO",
    "DexTokenSignalDTO",
    "DexTransactionDTO",
    "DexTransactionQuoteDTO",
    "DexUrls",
    "DisplayItem",
    "DqueryBatchPriceRequestDTO",
    "DqueryBatchTokenRequestDTO",
    "DqueryHoldersDetailRequestDTO",
    "DqueryHoldersRequestDTO",
    "DqueryMarketRequestDTO",
    "DqueryMemeRequestDTO",
    "ExchangeAssetsResponseModel",
    "ExchangeAssetsWalletsResponseModel",
    "ExchangeBatchRequestDTO",
    "ExchangeHistoricalQuotesCurrencyQuoteObject",
    "ExchangeHistoricalQuotesExchangeObject",
    "ExchangeHistoricalQuotesNtervalQuoteObject",
    "ExchangeHistoricalQuotesQuoteCurrencyMap",
    "ExchangeHistoricalQuotesResponseModel",
    "ExchangeHistoricalQuotesResultsMap",
    "ExchangeListingsLatestExchangeObject",
    "ExchangeListingsLatestQuoteMap",
    "ExchangeListingsLatestQuoteObject",
    "ExchangeListingsLatestResponseModel",
    "ExchangeMapExchangeObject",
    "ExchangeMapExchangeObjectStatus",
    "ExchangeMapResponseModel",
    "ExchangeMarketPairsLatestMarketPairExchangeReportedQuote",
    "ExchangeMarketPairsLatestMarketPairInfoObject",
    "ExchangeMarketPairsLatestMarketPairInfoObjectCategory",
    "ExchangeMarketPairsLatestMarketPairInfoObjectFeeType",
    "ExchangeMarketPairsLatestMarketPairQuote",
    "ExchangeMarketPairsLatestMarketPairQuoteObject",
    "ExchangeMarketPairsLatestPairBaseCurrencyInfoObject",
    "ExchangeMarketPairsLatestPairBaseCurrencyInfoObject1",
    "ExchangeMarketPairsLatestPairBaseCurrencyInfoObject1CurrencyType",
    "ExchangeMarketPairsLatestPairBaseCurrencyInfoObjectCurrencyType",
    "ExchangeMarketPairsLatestResponseModel",
    "ExchangeMarketPairsLatestResultsObject",
    "ExchangeQuoteDTO",
    "ExchangeQuotesLatestExchangeObject",
    "ExchangeQuotesLatestExchangeResultsMap",
    "ExchangeQuotesLatestQuoteMap",
    "ExchangeQuotesLatestQuoteObject",
    "ExchangeQuotesLatestResponseModel",
    "ExchangesInfoExchangeInfoObject",
    "ExchangesInfoResponseModel",
    "ExchangesInfoResultsMap",
    "ExchangesInfoURLsObject",
    "FCASListingsLatestCryptocurrencyObject",
    "FCASListingsLatestResponseModel",
    "FCASQuoteLatestCryptocurrencyObject",
    "FCASQuoteLatestCryptocurrencyResultsMap",
    "FCASQuoteLatestResponseModel",
    "FearAndGreedHistoricalFearAndGreedObject",
    "FearAndGreedHistoricalResponseModel",
    "FearAndGreedLatestResponseModel",
    "FearAndGreedLatestResponseObject",
    "FearGreedHistoricalDTO",
    "FearGreedLatestDTO",
    "FiatMapFiatObject",
    "FiatMapResponseModel",
    "GainerLeaderBoardResponseDTO",
    "GetV1AltcoinSeasonIndexHistoricalTimeframe",
    "GetV1ContentLatestLanguage",
    "GetV1CryptocurrencyAirdropsStatus",
    "GetV1CryptocurrencyListingsHistoricalCryptocurrencyType",
    "GetV1CryptocurrencyListingsHistoricalSort",
    "GetV1CryptocurrencyListingsHistoricalSortDir",
    "GetV1CryptocurrencyListingsLatestCryptocurrencyType",
    "GetV1CryptocurrencyListingsLatestSort",
    "GetV1CryptocurrencyListingsLatestSortDir",
    "GetV1CryptocurrencyListingsLatestTag",
    "GetV1CryptocurrencyListingsNewSortDir",
    "GetV1CryptocurrencyMapSort",
    "GetV1CryptocurrencyMarketpairsLatestCategory",
    "GetV1CryptocurrencyMarketpairsLatestFeeType",
    "GetV1CryptocurrencyMarketpairsLatestSort",
    "GetV1CryptocurrencyMarketpairsLatestSortDir",
    "GetV1CryptocurrencyOhlcvHistoricalInterval",
    "GetV1CryptocurrencyOhlcvHistoricalTimePeriod",
    "GetV1CryptocurrencyQuotesHistoricalInterval",
    "GetV1CryptocurrencyTrendingGainerslosersSort",
    "GetV1CryptocurrencyTrendingGainerslosersSortDir",
    "GetV1CryptocurrencyTrendingGainerslosersTimePeriod",
    "GetV1CryptocurrencyTrendingLatestTimePeriod",
    "GetV1CryptocurrencyTrendingMostvisitedTimePeriod",
    "GetV1ExchangeListingsLatestCategory",
    "GetV1ExchangeListingsLatestMarketType",
    "GetV1ExchangeListingsLatestSort",
    "GetV1ExchangeListingsLatestSortDir",
    "GetV1ExchangeMapSort",
    "GetV1ExchangeMarketpairsLatestCategory",
    "GetV1ExchangeMarketpairsLatestFeeType",
    "GetV1ExchangeQuotesHistoricalInterval",
    "GetV1FiatMapSort",
    "GetV1GlobalmetricsQuotesHistoricalInterval",
    "GetV2CryptocurrencyMarketpairsLatestCategory",
    "GetV2CryptocurrencyMarketpairsLatestFeeType",
    "GetV2CryptocurrencyMarketpairsLatestSort",
    "GetV2CryptocurrencyMarketpairsLatestSortDir",
    "GetV2CryptocurrencyOhlcvHistoricalInterval",
    "GetV2CryptocurrencyOhlcvHistoricalTimePeriod",
    "GetV2CryptocurrencyQuotesHistoricalInterval",
    "GetV3CryptocurrencyListingsLatestResponse200",
    "GetV3CryptocurrencyQuotesHistoricalInterval",
    "GetV5CryptocurrencyDerivativesMarketPairsListLatestCategory",
    "GetV5CryptocurrencyDerivativesMarketPairsListLatestCenterType",
    "GetV5CryptocurrencyDerivativesMarketPairsListLatestFeeType",
    "GetV5CryptocurrencyDerivativesMarketPairsListLatestSort",
    "GetV5CryptocurrencyDerivativesMarketPairsListLatestSortDir",
    "GetV5DerivativesLiquidationsCryptocurrencyListLatestSort",
    "GetV5DerivativesLiquidationsCryptocurrencyListLatestSortDir",
    "GetV5DerivativesLiquidationsExchangeListLatestSort",
    "GetV5DerivativesLiquidationsExchangeListLatestSortDir",
    "GetV5ExchangeDerivativesListSort",
    "GetV5ExchangeDerivativesListSortDir",
    "GetV5ExchangeDerivativesMarketPairsListLatestCategory",
    "GetV5ExchangeDerivativesMarketPairsListLatestFeeType",
    "GetV5ExchangeDerivativesMarketPairsListLatestSort",
    "GetV5ExchangeDerivativesMarketPairsListLatestSortDir",
    "GetV5RealWorldAssetsAssetsListAssetType",
    "GetV5RealWorldAssetsAssetsListSort",
    "GetV5RealWorldAssetsAssetsListSortDir",
    "GetV5RealWorldAssetsMapAssetType",
    "GetV5RealWorldAssetsMapSort",
    "GetV5RealWorldAssetsMarketPairsListSort",
    "GetV5RealWorldAssetsMarketPairsListSortDir",
    "GlobalMetricsBatchRequestDTO",
    "GlobalMetricsQuoteDTO",
    "GlobalMetricsQuotesHistoricCurrencyQuoteObject",
    "GlobalMetricsQuotesHistoricIntervalQuoteObject",
    "GlobalMetricsQuotesHistoricQuoteCurrencyMap",
    "GlobalMetricsQuotesHistoricResponseModel",
    "GlobalMetricsQuotesHistoricResultsObject",
    "GlobalMetricsQuotesLatestQuoteMap",
    "GlobalMetricsQuotesLatestQuoteObject",
    "GlobalMetricsQuotesLatestResponseModel",
    "GlobalMetricsQuotesLatestResultsObject",
    "HolderCountVO",
    "HolderDetailVO",
    "HolderDexVO",
    "HolderTagCountVO",
    "HolderTagItem",
    "HolderTrendVO",
    "HTTPStatus400ErrorObject",
    "HTTPStatus401ErrorObject",
    "HTTPStatus403ErrorObject",
    "HTTPStatus429ErrorObject",
    "HTTPStatus500ErrorObject",
    "IndexDetailDTO",
    "IndexHistoricalDTO",
    "IndexLatestDTO",
    "LeaderboardFilterDTO",
    "LeaderboardFilterDTOBoostType",
    "LiquidationsByCryptocurrencyResponseModel",
    "LiquidationsByCryptocurrencyResultsObject",
    "LiquidationsByCryptocurrencyResultsObjectCryptocurrenciesItem",
    "LiquidationsByCryptocurrencyResultsObjectCryptocurrenciesItemQuotesItem",
    "LiquidationsByExchangeResponseModel",
    "LiquidationsByExchangeResultsObject",
    "LiquidationsByExchangeResultsObjectExchangesItem",
    "LiquidationsByExchangeResultsObjectExchangesItemQuotesItem",
    "LiquidationsTotalResponseModel",
    "LiquidationsTotalResultsObject",
    "LiquidationsTotalResultsObjectQuotesItem",
    "LiquidityChangeDTO",
    "LiquidityChangeListResponseDTO",
    "MemeCoinFilterDTO",
    "MemeCoinResponseDTO",
    "MemeCoinResultDTO",
    "Model1",
    "Model2",
    "Model3",
    "Model4",
    "NetworkInfoDTO",
    "NewTokenLeaderBoardResponseDTO",
    "NextUnlockedDetailDTO",
    "NextUnlockedDTO",
    "OhlcvBatchRequestDTO",
    "Owner",
    "Plan",
    "Platform",
    "PlatformAddress",
    "PlatformDTO",
    "PlatformType0",
    "ProApiResponseStatus",
    "Quote",
    "RangeFilterDto",
    "ResponseStatus",
    "RWAAssetListResponseModel",
    "RWAAssetListResultsObject",
    "RWAAssetListResultsObjectRwaAssetsItem",
    "RWAAssetListResultsObjectRwaAssetsItemAssetType",
    "RWAAssetListResultsObjectRwaAssetsItemQuotesItem",
    "RWAIDMapResponseModel",
    "RWAIDMapResultsObject",
    "RWAIDMapResultsObjectRwaAssetsItem",
    "RWAIDMapResultsObjectRwaAssetsItemAssetType",
    "RWAInfoResponseModel",
    "RWAInfoResultsObject",
    "RWAInfoResultsObjectRwaAssetsItem",
    "RWAInfoResultsObjectRwaAssetsItemAbout",
    "RWAInfoResultsObjectRwaAssetsItemAssetType",
    "RWAIssuerResponseModel",
    "RWAIssuerResultsObject",
    "RWAIssuerResultsObjectTokensItem",
    "RWAIssuersListResponseModel",
    "RWAIssuersListResultsObject",
    "RWAIssuersListResultsObjectIssuersItem",
    "RWAMarketPairsResponseModel",
    "RWAMarketPairsResultsObject",
    "RWAMarketPairsResultsObjectMarketPairsItem",
    "RWAMarketPairsResultsObjectMarketPairsItemCategory",
    "RWAMarketPairsResultsObjectMarketPairsItemExchange",
    "RWAMarketPairsResultsObjectMarketPairsItemExchangeReportedQuotesItem",
    "RWAMarketPairsResultsObjectMarketPairsItemFeeType",
    "RWAMarketPairsResultsObjectMarketPairsItemMarketPairBase",
    "RWAMarketPairsResultsObjectMarketPairsItemMarketPairBaseCurrencyType",
    "RWAMarketPairsResultsObjectMarketPairsItemMarketPairQuote",
    "RWAMarketPairsResultsObjectMarketPairsItemMarketPairQuoteCurrencyType",
    "RWAMarketPairsResultsObjectMarketPairsItemQuotesItem",
    "RWAQuotesLatestResponseModel",
    "RWAQuotesLatestResultsObject",
    "RWAQuotesLatestResultsObjectRwaAssetsItem",
    "RWAQuotesLatestResultsObjectRwaAssetsItemAssetType",
    "RWAQuotesLatestResultsObjectRwaAssetsItemQuotesItem",
    "RWAQuotesLatestResultsObjectRwaAssetsItemTokensItem",
    "RWAQuotesLatestResultsObjectRwaAssetsItemTradfiMarketsItem",
    "RWAQuotesLatestResultsObjectRwaAssetsItemTradfiMarketsItemExchange",
    "SearchResponseDTO",
    "SearchResultDTO",
    "SecurityItem",
    "SecurityScan3RdResult",
    "SecurityScanAggregatedResult",
    "SecurityScanResult",
    "SimplePriceItemObject",
    "SimplePriceResponseModel",
    "SnapshotBatchQueryRequestDTO",
    "Status",
    "Status1",
    "Status2",
    "Status3",
    "Status4",
    "Status4ErrorCode",
    "SwapListResponseDTO",
    "TagDTO",
    "TheBlockchainPlatformWhereTheAssetsAreHeldOn",
    "TheCryptocurrencyOfTheHoldingsInTheWallet",
    "Token",
    "TokenDetailDTO",
    "TokenEventDTO",
    "TokenLeaderboardDTO",
    "TokenLiquiditySnapshotDTO",
    "TokenPriceDTO",
    "TokenSecurityResponseDTO",
    "TokenStatsDTO",
    "TokenTopPoolDTO",
    "TokenUnlockEventDTO",
    "TokenUnlockInfoDTO",
    "ToolsPriceConversionQuoteObject",
    "ToolsPriceConversionQuotesMapPleaseNoteThisWillBeWrappedInAnArrayIfYouRequestBySymbolUsingTheV2Endpoint",
    "ToolsPriceConversionResponseModel",
    "ToolsPriceConversionResultsObject",
    "TradeHistoryDTO",
    "TrendingTokensResponseDTO",
    "Usage",
    "V2SimplePriceItemObject",
    "V2SimplePriceItemObjectQuotesItem",
    "V2SimplePriceResponseModel",
)
